version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo apt install python3 -y
            sudo apt install virtualenv -y
            virtualenv my_venv
            cd my_venv
            source bin/activate
            pip3 install pytest
            pytest ../test_tests.py

  cleanup:
    executor: docker-executer
    steps:
        -run:
            echo "cleaning up"


workflows:
  main:
    jobs:
      - build-and-test
      - cleanup
